# Generated by Django 2.2.1 on 2019-05-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_article', '0005_article_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.CharField(max_length=500),
        ),
    ]
