# Generated by Django 2.2 on 2019-06-05 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_article', '0007_auto_20190508_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='star_article',
            options={'ordering': ('article',)},
        ),
    ]
